version: '3.8'

services:
  broadcaster:
    build:
      context: ./hello_broadcaster
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  receiver:
    build:
      context: ./hello_receiver
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - broadcaster
