apiVersion: v1
kind: Service
metadata:
  name: hello-broadcaster-service
spec:
  type: NodePort
  selector:
    app: hello-broadcaster
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000
