apiVersion: v1
kind: Service
metadata:
  name: hello-receiver-service
spec:
  type: NodePort
  selector:
    app: hello-receiver
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 30001  
